[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[features]
default = []
metal = ["candle-core/metal", "candle-nn/metal"]

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-datasets = "0.9.1"
anyhow = "1.0.90"
tokenizers = "0.20.3"
fastrand = "2.0"
