[workspace]
members = [
    "core",
    "tokenization",
    "training",
    "utils"
]

[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[features]
default = []
metal = ["candle-core/metal", "candle-nn/metal", "cascade-core/metal"]

[dependencies]
anyhow = "1.0.90"
cascade-core = { path = "core" }
cascade-training = { path = "training" }
transformer-tokenization = { path = "tokenization" }
candle-core = "0.9.1"
candle-nn = "0.9.1"
utils = { path = "utils" }
