[workspace]
resolver = "2"
members = [
    "crates/pretraining-data",
    "crates/tokenizer",
    "crates/embedding",
    "crates/attention",
    "crates/layers",
    "crates/model",
    "crates/training",
]
