[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { version = "0.9.1", features = ["metal"] }
candle-nn = { version = "0.9.1", features = ["metal"] }
candle-datasets = "0.9.1"
anyhow = "1.0.90"
tokenizers = "0.20.3"
fastrand = "2.0"
