[workspace]
members = [
    "crates/pretraining-data",
    "crates/tokenizer",
    "crates/embedding",
]

[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "transformer"
path = "main.rs"

[dependencies]
pretraining-data = { path = "crates/pretraining-data" }
tokenizer = { path = "crates/tokenizer" }
embedding = { path = "crates/embedding" }
