[package]
name = "pretraining-data"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "preprocess"
path = "src/bin/preprocess.rs"

[dependencies]
serde_json = "1.0"
rayon = "1.10"

[dev-dependencies]
tempfile = "3.0"
