---
# M3-friendly transformer configuration (~22M parameters)

model:
  hidden_size: 384
  intermediate_size: 1536
  num_layers: 6
  num_attention_heads: 6
  num_key_value_heads: 6
  max_position_embeddings: 512
  attn_dropout: 0.02
  residual_dropout: 0.02
  rope_mode: null
  rope_theta: null

tokenizer:
  # Update these paths once the orchestrator generates artifacts for this run.
  tokenizer_json: "../runs/m3-medium/tokenizer/tokenizer.json"
  vocab: null
  merges: null
  special_tokens: "../runs/m3-medium/special_tokens.txt"

data:
  train_shards:
    - "../crates/pretraining-data/input.txt"
  validation_shards:
    - "../crates/pretraining-data/input.txt"
  batch_size: 6
  gradient_accumulation_steps: 1
  shuffle_buffer_size: 1024
  cache_dir: null

optimizer:
  algorithm: adam_w
  learning_rate: 8.0e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  epsilon: 1.0e-8

scheduler:
  strategy: cosine_with_warmup
  warmup_steps: 500
  total_steps: 10000
  total_epochs: null
  min_lr: 1.0e-5
  max_lr: null

runtime:
  seed: 42
  precision: fp32
  log_every_n_steps: 20
  checkpoint:
    directory: "../runs/m3-medium/checkpoints"
    every_n_steps: 500
    every_n_epochs: null
    max_keep: 3
  evaluation:
    every_n_steps: 1000
    every_n_epochs: null
    max_batches: 4
    best:
      directory: "../runs/m3-medium/best"
      max_keep: 1
  logging:
    enable_stdout: true
    tensorboard: "../runs/m3-medium/tensorboard"
    tensorboard_flush_every_n: 50
