[package]
name = "training"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.9.1" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.9.1" }
model = { path = "../model" }
tokenizer = { path = "../tokenizer" }
pretraining-data = { path = "../pretraining-data" }
attention = { path = "../attention" }
layers = { path = "../layers" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"
futures = "0.3"
rand = { version = "0.8", features = ["std"] }
tokenizers = "0.22"
